spring:
  cloud:
    gateway:
      routes:
      - id: servicio-personas
        uri: lb://servicio-personas
        predicates:
          - Path=/api/personas/**
        filters:
          - StripPrefix=2
eureka:                  
 client:
  serviceUrl:
   defaultZone: http://localhost:8761/eureka  
